# This is a basic workflow to help you get started with Actions

name: push public file to coding

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
  
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: replace secrets in config.toml
        run: |
          sed -i 's/<TWIKOO_ENVID>/${{ secrets.TWIKOO_ENVID }}/g' config.toml
          sed -n '/envId/p' config.toml

      - name: Run Hugo
        run: hugo --minify

      - name: Deploy to coding
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: ${{ secrets.CODING_REPO }}
          BRANCH: master
          FOLDER: public
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KNOWN_HOSTS_FILE: resources/known_hosts
          MESSAGE: "[Github Action] Update the content to the commit {sha} that had the message: {msg}"

      - name: Upload Hugo Algolia Index
        uses: aoudiamoncef/hugo-algolia-uploader@main
        with:
          # Such as `LAHZOUZT15`. Required
          app_id: 9RO7ER2GPK
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ALGOLIA_ADMIN_KEY }} . Required
          admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          # The index name. Required
          index_name: 'summinglearn_index'
          # The index name separator. If multi languages is enabled. Default value is`_` 
          #index_name_separator: <your_index_name_separator>
          # The index file directory relative to repo root. Default value is `public`
          #index_file_directory: <your_index_file_directory>
          # The index file name. Default value is `index.json`
          #index_file_name: <your_index_file_name>
          # The indexes i18next language codes comma separated. Ex: en,fr,tzm will upload to 3 indexes with predefined suffix: 'your_index_name + index_name_separator + your_index_language'
          #index_languages: <your_index_languages>